#!/usr/bin/perl
# Generate public_keys.h from keyfile

use File::Basename;

use strict;

my $keyfile = shift;

my $input_name = basename($keyfile);

my $headers_file = "public_keys.h";

open(my $fh, '<:raw', $keyfile) or die("key file open error!");

# skip first byte of keyfile
my $n = read($fh, my $skip, 1);

open(my $fout, ">", $headers_file) or die("Can't open $headers_file for writing!");
print $fout "// This file is autogenerated! Use generate_header_keys.pl to create!\n// $input_name\n";
print $fout "const unsigned char default_airtag_key[][28] = {\n";

while(read($fh, my $newkey, 28) == 28) {
  my @key = unpack("C*", $newkey);

  print $fout "  {\n";
  # Print key in 4 lines of 7 bytes each
  for my $i (0..3) {
    print $fout "    ";
    for my $j (0..6) {
      printf $fout "0x%02X, ", $key[$i * 7 + $j];
    }
    print $fout "\n";
  }
  print $fout "  },\n";
}

print $fout "};\n\n";

print $fout "const unsigned char default_fmdn_key[20] = {\n";
print $fout "  0, 0, 0, 0, 0,\n";
print $fout "  0, 0, 0, 0, 0,\n";
print $fout "  0, 0, 0, 0, 0,\n";
print $fout "  0, 0, 0, 0, 0,\n";
print $fout "};\n\n";
close($fout);
close($fh);
