// This file is autogenerated! Use generate_header_keys.pl to create!
// if all zeros - keys will be ignored!
const unsigned char default_airtag_key[][28] = {
  {
    0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 
  },
};

const unsigned char default_fmdn_key[20] = {
  0, 0, 0, 0, 0,
  0, 0, 0, 0, 0,
  0, 0, 0, 0, 0,
  0, 0, 0, 0, 0,
};
